### ISSUE TITLE
intcomma() variant needed to handle money

### ISSUE THREAD

**Issue by kfmfe04** [jmoiron/humanize#118]
When using intcomma on a dollar value like 14308.40, I get '14,308.4'.

It would be nice to have a moneycomma(14308.40,2) which gives me '14,308.40'.

**Comment by hugovk** [comment]
I added an `ndigits` option to `intcomma` in https://github.com/jmoiron/humanize/pull/123. Please could you have a look and let me know what you think?

**Comment by kfmfe04** [comment]
Just pulled it out and tried it out.  Thank you - works perfectly.

**Comment by hugovk** [comment]
Good to hear, thanks for testing!
