### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by hugovk** [jmoiron/humanize#130]
CPython 3.5 reaches end-of-life on 2020-09-13.

* https://www.python.org/downloads/

Humanize will also drop support for Python 3.5 around the same time.

I'm considering this won't need a major version bump, as the `python_requires` will be updated so people still on 3.5 will get the last release that did support it.

```diff
-    python_requires=">=3.5",
+    python_requires=">=3.6",
     # Get strings from https://pypi.org/pypi?%3Aaction=list_classifiers
     classifiers=[
         "Development Status :: 5 - Production/Stable",
         "Intended Audience :: Developers",
         "License :: OSI Approved :: MIT License",
         "Operating System :: OS Independent",
         "Programming Language :: Python",
         "Programming Language :: Python :: 3",
-        "Programming Language :: Python :: 3.5",
         "Programming Language :: Python :: 3.6",
         "Programming Language :: Python :: 3.7",
         "Programming Language :: Python :: 3.8",
         "Programming Language :: Python :: 3 :: Only",
```

**Comment by hugovk** [comment]
Here's the pip installs for humanize from PyPI for May 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  36.00% |   367,639 |
| 3.7      |  29.64% |   302,764 |
| 2.7      |  16.01% |   163,475 |
| 3.8      |  11.41% |   116,565 |
| 3.5      |   6.19% |    63,198 |
| null     |   0.60% |     6,158 |
| 3.4      |   0.11% |     1,102 |
| 3.9      |   0.04% |       377 |
| 2.6      |   0.00% |        13 |
| 3.10     |   0.00% |         9 |
| Total    |         | 1,021,300 |

Source: `pip install -U pypistats && pypistats python_minor humanize --last-month`

Another option is to follow NEP 29, which would suggest supporting 3.6+ already now, and 3.7+ from 2020-06-23:

* https://numpy.org/neps/nep-0029-deprecation_policy.html

Comments welcome!

**Comment by robvdl** [comment]
I'd watch out with dropping support for 3.6 as you're talking Ubuntu Bionic here which is still a very active LTS version of Ubuntu, dropping 3.6 would annoy too many users but I agree dropping 3.5 is acceptable.

**Comment by ju-sh** [comment]
Looks like a lot of people still use humanize with python2.7. Is 2.7 still supported?

**Comment by hugovk** [comment]
No, Python 2.7 has been EOL since 2020-01-01.

16% is low when comparing with other projects which have also dropped Python 2, and for people still needing 2.7 it's still possible to install the last humanize that did support it.

**Comment by hugovk** [comment]
Thanks for the feedback, let's keep Python 3.6 for a bit longer.

July 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  33.92% |   348,699 |
| 3.7      |  33.89% |   348,385 |
| 3.8      |  15.59% |   160,277 |
| 2.7      |  12.47% |   128,228 |
| 3.5      |   3.39% |    34,822 |
| null     |   0.63% |     6,441 |
| 3.4      |   0.08% |       826 |
| 3.9      |   0.01% |       145 |
| 3.10     |   0.01% |       138 |
| 2.6      |   0.00% |         5 |
| 3.3      |   0.00% |         1 |
| Total    |         | 1,027,967 |

Source: `pip install -U pypistats && pypistats python_minor humanize --last-month`

**Comment by hugovk** [comment]
> I'm considering this won't need a major version bump, as the `python_requires` will be updated so people still on 3.5 will get the last release that did support it.

Any thoughts on this?

**Comment by hugovk** [comment]
No feedback on whether to bump, will bump for the extra clarity it brings. Releasing 3.0.0 now.
