### ISSUE TITLE
Incorrect expected value of `fractional(0.333)` in the readme

### ISSUE THREAD

**Issue by eldipa** [jmoiron/humanize#133]
### What did you do?

I ran [byexample](https://byexamples.github.io/byexample/) to verify the examples in the readme:

```shell
byexample -l python README.md
```

I also confirmed the issue running the example in a python console.

### What did you expect to happen?

The readme says:

```
>>> humanize.fractional(0.333)
'1/3'
```

### What actually happened?

Instead of `'1/3'` it returns `'333/1000'`

The value returned is probably the correct one, I think that the readme should be updated.

### What versions are you using?

* OS: Debian 9
* Python: Python 3.5
* Humanize: master

**Comment by hugovk** [comment]
Thanks! I've made PR #134 to fix this.
