### ISSUE TITLE
Add documentation on Read the Docs

### ISSUE THREAD

**Issue by hugovk** [jmoiron/humanize#139]
Generate docs from source and docstrings.

There's an example guide here:

* https://cjolowicz.github.io/posts/hypermodern-python-05-documentation/

**Comment by hugovk** [comment]
@jmoiron Hello!

I've created API reference documentation (#147, #148).

It's currently hosted from my fork at https://python-humanize.readthedocs.io

Please could you add me as a maintainer to https://humanize.readthedocs.io and I'll hook it up to build docs direct from this repo?

* [ ] Please add `hugovk` at https://readthedocs.org/dashboard/humanize/users/

Thanks!

**Comment by carterbox** [comment]
Readthedocs has an abandoned-project policy which could be used to get access since it seems like @jmoiron is unreachable. https://docs.readthedocs.io/en/stable/abandoned-projects.html

**Comment by hugovk** [comment]
Good to know, thanks! I'll drop Jason an email and if no reply will follow the RTD policy :)

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
