### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by hugovk** [jmoiron/humanize#143]
One oddity to me is the rounding. While I can understand that

```python
humanize.naturaltime(2*365*24*60*60 - 1)
```

is `1 year, 11 months ago` and not `2 years ago`, because the year is not complete yet and we don't celebrate birthdays early ("how long ago was it?" - "2 years?" - "not yet!"), my intuitive expectation of 

```python
humanize.naturaldelta(2*365*24*60*60 - 1)
```

is actually `2 years` - because with deltas ("how long did it take?"), I feel rounding is much more natural.

So for `101_943 / 1_000_000`, I'd probably expect `102 milliseconds`.

_Originally posted by @bersbersbers in https://github.com/jmoiron/humanize/issues/75#issuecomment-659220243_

**Comment by ssbarnea** [comment]
I totally agree that current behavior is flawed, I had a duration of ~170 days which counts for 5.7 months, clearly something to be rounded up but it reported "5 months".

**Comment by hugovk** [comment]
@bersbersbers @ssbarnea Please could you have a look at https://github.com/jmoiron/humanize/pull/154 and see if it does the right sort of thing? Thanks!

**Comment by bersbersbers** [comment]
I will try it once it published, but I don't have the bandwidth right now to check that PR closely. At first sight, it does make sense.

**Comment by hugovk** [comment]
No problem, thanks for the quick check! 

In case it helps, it's possible to pip install from the Git branch like this:

```sh
pip install git+https://github.com/hugovk/humanize.git@naturaldelta-rounding
```

**Comment by bersbersbers** [comment]
That does help, thanks. A fews that I did revealed these unexpected ones:

```
>>> humanize.naturaldelta(2*365*24*60*60-1)
'2 years'
>>> humanize.naturaldelta(1*365*24*60*60-1)
'1 year, 364 days'
```

I did not test further as it seems an error needs to be fixed first.

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
