### ISSUE TITLE
1024*1024*1024 = 1.1 GB?

### ISSUE THREAD

**Issue by johnmudd** [jmoiron/humanize#145]
### What did you do?
```pycon
>>> humanize.naturalsize(1024*1024*1024)
```

### What did you expect to happen?
```pycon
>>> humanize.naturalsize(1024*1024*1024)
'1.0 GB'
```

### What actually happened?
```pycon
>>> humanize.naturalsize(1024*1024*1024)
'1.1 GB'
```

### What versions are you using?
```pycon
>>> humanize.__version__
'1.0.0'
```

* OS: Linux
* Python: 2.7
* Humanize: 1.0.0

**Comment by hugovk** [comment]
By default, it uses a decimal base 1000. For binary base 1024, set the `gnu` or `binary` parameter to `True`:

https://github.com/jmoiron/humanize/blob/56a06434c5e7026c70e674ec45975e5e27ae7e70/src/humanize/filesize.py#L12-L34
