### ISSUE TITLE
[Request] Humanizing distances

### ISSUE THREAD

**Issue by calina-c** [jmoiron/humanize#152]
### What I want to do
Humanize distances between two points (see Distance object https://docs.djangoproject.com/en/3.1/ref/contrib/gis/measure/#distance)

### Why it makes sense
For short distances it makes sense to have approximations in meters, for longer distances in kilometres or miles. It is also weird-looking to show the exact distance, e.g. 2392.324553 km. Then we have the locale issue where some countries prefer miles over kilometers.

I have been looking for some formulae online but can't find any best practices or libraries for this. I noticed that maps applications have this behaviour, but I can't find any specs to it.

Do you think such a function would be useful in humanize? Do you know of any specs/best practices? I am more than happy to do the implementation, if you think it is worth it, and if you can help with the full definition of this task.

**Comment by hugovk** [comment]
> Do you think such a function would be useful in humanize?

Yes, sounds useful!

> Do you know of any specs/best practices? I am more than happy to do the implementation, if you think it is worth it, and if you can help with the full definition of this task.

I don't know of any, what sort of thing would be useful for you?

Maybe something along the lines of:

Input in metres.

* < 0.01 metre: "x millimetres"
* < 1 metre: "x centimetres"
* 1-999m: "x metres"
* 1,000m+ "x.y kilometres"
* 100,000m+ "x kilometres" (or perhaps even from 10,000m+?)

If rounding needed, round to the nearest.

It would be useful to include a parameter to decide whether to use Commonwealth spelling ("metre") or American ("meter") or abbreviations ("m"), but that could be added afterwards.

(We could just do metric first and add imperial later, if you prefer. Perhaps the same parameter could perhaps be used to choose imperial units for output too, and if necessary convert metric to imperial.)

Thanks!

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
