### ISSUE TITLE
Description without documentation

### ISSUE THREAD

**Issue by nubonics** [jmoiron/humanize#162]
Problem: Turn a saying suchas `3 minutes ago` into something readable by a program.... this is what this libraries original intention was to solve, however, there is ZERO documentation on how to do so.

**Comment by hugovk** [comment]
Hello, the README begins:

> This modest package contains various common humanization utilities, like turning a number into a fuzzy human readable duration ("3 minutes ago") or into a human readable size or throughput.  

It sounds like you're after something to do the reverse, is that right? Turn a fuzzy human readable string into a number? 

I don't think that was this library's original intention, but would be happy to update the docs to link to a "computerise" library if you find one.

**Comment by nubonics** [comment]
No worries, with a bit of splitting, i was able to do this with arrow
