### ISSUE TITLE
Declare Python 3.9 support

### ISSUE THREAD

**Issue by hugovk** [jmoiron/humanize#166]
Python 3.9.0 is due out on Monday (https://www.python.org/dev/peps/pep-0596/).

We're already testing against `3.9-dev`, so let's also declare support for Python 3.9.

Add the 3.9 Trove classifier to `setup.py`, and also `py39` to `tox.ini`.

---

If doing this after the release: 

* Check if `3.9-dev` can be replaced with plain `3.9` in `.travis.yml`

* Also see if the `3.9-dev` line can be removed from `.github/workflows/test.yml` and replaced with `"3.9"` with the other non-devs.

Important: If doing these, please enable the CIs on your fork and make sure they pass before submitting the PR.

* [x] Travis CI
* [x] GitHub Actions
* [x] Trove classifier
* [x] Tox

**Comment by jaimcamp** [comment]
Hi, could I take this one?

**Comment by hugovk** [comment]
@jaimcamp Certainly!

**Comment by hugovk** [comment]
@jaimcamp How did you get on?

**Comment by jaimcamp** [comment]
Hi @hugovk , I have been waiting Travis support for 3.9 for a while now. 
It's still not there (https://docs.travis-ci.com/user/languages/python/#python-versions), but I have opened a WIP PR, which can be merged as soon as Travis adds support for 3.9 https://github.com/jmoiron/humanize/pull/171

**Comment by hugovk** [comment]
Travis CI now has `3.9` available.

**Comment by jaimcamp** [comment]
Added it again in https://github.com/jmoiron/humanize/pull/176 .
