### ISSUE TITLE
Support for parsing

### ISSUE THREAD

**Issue by dfurrer** [jmoiron/humanize#173]
Hi

I'm looking for an open source library that can do human-friendly formatting as well as parsing. I'm interested in byte sizes and datetime for now. Would you be open to adding this?

D

**Comment by hugovk** [comment]
Please could you give more info about what you're thinking of? Some examples would help. Thanks!

**Comment by dfurrer** [comment]
Sure, basically I have a command line tool where I can specify data size via flags and currently it expects bytes so if I want 10GB I have to invoke it with:

tool --data_size=1000000000

I'd rather be able to say

tool --data_size=10gb

So I'd want the reverse of naturalsize()

**Comment by hugovk** [comment]
So a bit like "robotize" or "dehumanize". I think it's come up before (can't find the issue now) and I can see that would be useful, but I think it would be better to keep this library focused on the one direction. 

Thank you for the suggestion, and if you find something useful, I'd be happy to link to it from the docs.

**Comment by dfurrer** [comment]
Hmm, you could call it "robotize" or "dehumanize" but really the purpose is still to make it easier humans & machines to exchange numbers/quantities which should go both ways, i.e. on input as well as on output.

Anyway I think I found what I need:
https://github.com/xolox/python-humanfriendly
