### ISSUE TITLE
Question on precisedelta

### ISSUE THREAD

**Issue by matrix2113** [jmoiron/humanize#184]
### What did you do?

I tried to use precise timing with suppress and minimum_time.

### What did you expect to happen?

I wanted it to show a date like `3 years and 7 months ago`

### What actually happened?

It returns `3 years and 7.23 months ago`

### What versions are you using?

* OS: Ubuntu 20.04
* Python: 3.8.5
* Humanize: 3.1.0

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
    @commands.command()
    async def profile(self, ctx, user: discord.Member = None):
        if user is None:
            user = ctx.author

        embed = discord.Embed(colour=discord.Colour.purple(), timestamp=ctx.message.created_at,
                              title=f"User Info - {user}")
        embed.add_field(name="ID:", value=user.id, inline=False)
        embed.add_field(name="Highest Role:", value=user.top_role.mention)

        acc_creation = datetime.utcnow() - user.created_at
        created_acc = humanize.precisedelta(acc_creation, suppress=["days", "hours", "minutes", "seconds"])
        embed.add_field(name="Created Account On:", value=user.created_at.strftime("%d %B %Y") + " (" + created_acc + ")")

        await ctx.send(embed=embed)
```

**Comment by hugovk** [comment]
From the [docs](https://python-humanize.readthedocs.io/en/latest/time/#humanize.time.precisedelta):

> A custom `format` can be specified to control how the fractional part is represented:
> 
```pycon
>>> precisedelta(delta, format="%0.4f")
'2 days, 1 hour and 33.1230 seconds'
```

So for example:

```pycon
>>> import humanize
>>> import datetime as dt
>>> delta = dt.timedelta(days=(365*3 + 30*7 + 12))
>>> delta
datetime.timedelta(days=1317)
>>> humanize.precisedelta(delta, suppress=["days", "hours", "minutes", "seconds"])
'3 years and 7.28 months'
>>> humanize.precisedelta(delta, suppress=["days", "hours", "minutes", "seconds"], format="%0.f")
'3 years and 7 months'
```

**Comment by matrix2113** [comment]
Thanks I appreciate it. You can close this issue.
