### ISSUE TITLE
naturaldelta should not round down the months

### ISSUE THREAD

**Issue by luisgc93** [jmoiron/humanize#186]
I've noticed this is the same issue as #116 but didn't find any discussion on why it was closed or why the current implementation is favoured. Apologies if this is somehow redundant. 

### What did you do?
`humanize.naturaldelta(datetime.date(2021, 3, 13) - datetime.date(2020, 12, 13))`
### What did you expect to happen?
I would expect the result to be `"3 months"`
### What actually happened?
The result was `"2 months"`
### What versions are you using?

* OS: macOS Catalina 10.15.7 
* Python: 3.8
* Humanize: 3.2.0

```python
from datetime import date
import humanize

time_difference = humanize.naturaldelta(date(2021, 3, 13) - date(2020, 12, 13)

assert time_difference == "3 months"

```

I'd be happy to make the relevant changes. Thanks in advance for any feedback!

**Comment by hugovk** [comment]
I'm not sure why #116 was closed, the reporter later deleted their account too. Anyway, is this a duplicate of https://github.com/jmoiron/humanize/issues/143?

I had started on a PR for that one (https://github.com/jmoiron/humanize/pull/154), but unfortunately I let it stall and it probably needs some refactoring. Anyway, I'd be happy if you'd like to take a look into it!

Feel free to use any of that PR, or just start afresh. At least, the test cases may be handy, and see the comments in #143 too.

Thanks!

**Comment by luisgc93** [comment]
I've taken a look at your PR, I like your approach. It also fixes the example I've outlined. Do I need write access permissions to make any changes?

**Comment by hugovk** [comment]
Please create a branch from mine into your owm fork, and then create a fresh PR. Thanks!

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
