### ISSUE TITLE
humanize.precisedelta raises IndexError with timedelta(seconds=0)

### ISSUE THREAD

**Issue by juliomalegria** [jmoiron/humanize#189]
`humanize.precisedelta` raises `IndexError` with an "empty" timedelta (i.e. 0 seconds). I'd have expected this to still return a string, or at least `None`. Worst-case scenario, if we don't want to alter the functionality, it'd be good to have a comment on the code to know what to expect.

### What did you do?

`precisedelta(timedelta(seconds=0))` or `humanize.precisedelta(0)`.

### What did you expect to happen?

I expected the result to be `'0 seconds'` or `'0 {minimum_unit}s'`.

### What actually happened?

Raised `IndexError`.

### What versions are you using?

* OS: macOS Catalina 10.15.7
* Python: 3.7.5
* Humanize: 2.6.0

Please include **code** that reproduces the issue.

```python
>>> from datetime import timedelta
>>> from humanize import precisedelta
>>> precisedelta(timedelta(seconds=0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/virtualenv/insights-py37/lib/python3.7/site-packages/humanize/time.py", line 501, in precisedelta
    tail = texts[-1]
IndexError: list index out of range
>>> precisedelta(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/virtualenv/insights-py37/lib/python3.7/site-packages/humanize/time.py", line 501, in precisedelta
    tail = texts[-1]
IndexError: list index out of range
```

**Comment by hugovk** [comment]
Please upgrade, this works for me with the latest 3.2.0:

```pycon
Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import timedelta
>>> from humanize import precisedelta
>>>
>>> precisedelta(timedelta(seconds=0))
'0 seconds'
>>> from humanize import __version__
>>> __version__
'3.2.0'
>>>
```
