### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by dsoprea** [jmoiron/humanize#190]
I've created this ticket when two others have been closed in the past to just have something open as a form of a bookmark for what is a real issue and quickly solveable. This is a problem, and I'm not sure why hacks must've been considered viable alternatives to just doing an easy fix to make this correct.

One such example, were the aware-naive thing breaks down is here:

```python
def naturaltime(value, future=False, months=True, minimum_unit="seconds"):

...

    now = _now()
    date, delta = date_and_delta(value, now=now)
```

Just allow `now` to be passed in and curried to `date_and_delta`, where it will already use a default _now_ time if not provided. So, for example, merely this:

```python
def naturaltime(value, future=False, months=True, minimum_unit="seconds", now=None):

...

    date, delta = date_and_delta(value, now=now)
```

Something like this will allows it to be resolved in at least a few obvious places while making it the caller's responsibility and not directly getting involved with any timezone management from this project.

Reference: https://github.com/jmoiron/humanize/issues/9

**Comment by mihiretab-taye** [comment]
### File to edit: humanize\time.py 

- Go to line 62 and modify the function with the below code.
- The update is the code in bold.

`def _date_and_delta(value, *, now=None):
    """Turn a value into a date and a timedelta which represents how long ago it was.

    If that's not possible, return `(None, value)`.
    """
    **try:
        value = value.replace(tzinfo=None)
    except:
        pass**
        
    if not now:
        now = _now()
    if isinstance(value, dt.datetime):
        date = value
        delta = now - value
    elif isinstance(value, dt.timedelta):
        date = now - value
        delta = value
    else:
        try:
            value = int(value)
            delta = dt.timedelta(seconds=value)
            date = now - delta
        except (ValueError, TypeError):
            return None, value
    return date, _abs_timedelta(delta)`

**Comment by mihiretab-taye** [comment]
### File to edit: humanize\time.py 

- Go to line 62 and modify the function by adding the below code.
```python

value = value.replace(tzinfo=None)
```

Then the edited function will be:

```python
def _date_and_delta(value, *, now=None):
    """Turn a value into a date and a timedelta which represents how long ago it was.

    If that's not possible, return `(None, value)`.
    """
    
    value = value.replace(tzinfo=None)
        
    if not now:
        now = _now()
    if isinstance(value, dt.datetime):
        date = value
        delta = now - value
    elif isinstance(value, dt.timedelta):
        date = now - value
        delta = value
    else:
        try:
            value = int(value)
            delta = dt.timedelta(seconds=value)
            date = now - delta
        except (ValueError, TypeError):
            return None, value
    return date, _abs_timedelta(delta)
```

**Comment by makeworld-the-better-one** [comment]
@mihiretab-taye you should make a PR if you've found a solution.

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
