### ISSUE TITLE
AttributeError: module 'humanize' has no attribute 'precisedelta'

### ISSUE THREAD

**Issue by Someone1123698** [jmoiron/humanize#191]
### What did you do?
I ran the following code on Google Colab
```python
delta = dt.timedelta(seconds=3478)
diff = humanize.precisedelta(delta, minimum_unit="microseconds")
print(diff)
```
And got an error
### What did you expect to happen?
print the output
### What actually happened?
raised an error: AttributeError: module 'humanize' has no attribute 'precisedelta'
### What versions are you using?

* OS: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
* Python: 3.7.10
* Humanize: 0.5.1

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
import datetime as dt
try:
    import humanize
except ImportError:
    !pip install humanize
finally:
    import humanize
delta = dt.timedelta(seconds=3478)
diff = humanize.precisedelta(delta, minimum_unit="microseconds")
print(diff)
```

**Comment by hugovk** [comment]
`precisedelta` was added in humanize 2.6.0 (August 2020).

* https://github.com/jmoiron/humanize/releases/tag/2.6.0

You're using 0.5.1 from November 2014.

Please upgrade to 2.6.0 or newer. Consider 3.3.0 from last month:

```sh
python3 -m pip install -U humanize
```
