### ISSUE TITLE
Manage plurals

### ISSUE THREAD

**Issue by jordimas** [jmoiron/humanize#193]
### What did you do?

humanize.intword(3000000)

### What did you expect to happen?

To show: "3 millions"

### What actually happened?

Shown: "3 millión"

In many languages numbers have plurals. For example:

* 1 milió
* 2 millions

Here: https://github.com/jmoiron/humanize/blob/master/src/humanize/number.py#L124

You need to support plurals. 

### What versions are you using?

* OS: Linux
* Python: 3.8
* Humanize: 3.3.0 

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
code goes here
```

**Comment by hugovk** [comment]
In English, we would still want to say "3 million", but happy to accept a PR to fix this for other languages, if it can be done such that it doesn't break existing translations. Thanks!
