### ISSUE TITLE
How to convert million, billion, trillion quadrillion in number

### ISSUE THREAD

**Issue by machinexa2** [jmoiron/humanize#218]
I know it can be done by multiplying with some numebers but it would be cool if some function does that. 
Lets say I have number 40 thousand then I need a function humanize_int('40 thousand') to convert that to 40,000. Same for million, billion and trillion.

**Comment by machinexa2** [comment]
ap number function is similar but doesnt work
```
>>> humanize.apnumber(100000)
'100000'
>>> 
```

**Comment by hugovk** [comment]
This is how `apnumber` works:

```pycon
>>> import humanize
>>> humanize.apnumber(4)
'four'
>>> humanize.apnumber(41)
'41'
```

You want to go from "human number" (40 thousand) to a "machine number" (40,000), but humanize only goes from machine to human (the clue is in the name ;)

Have a look at https://github.com/xolox/python-humanfriendly instead (re: https://github.com/jmoiron/humanize/issues/173#issuecomment-717382321).
