### ISSUE TITLE
Documentation shows private functions

### ISSUE THREAD

**Issue by samueljsb** [jmoiron/humanize#225]
The documentation lists some functions that are not available outside the submodule they are defined in. All of the usage examples use:

```python
import humanize

humanize.…
```

but this does not allow access to these methods.

These functions should be exported to the parent module.

**Comment by hugovk** [comment]
Please can you give a specific example with a link to the page in question?

**Comment by samueljsb** [comment]
The first two functions and the enum [on this page](https://python-humanize.readthedocs.io/en/latest/time/) are available from the module directly bu not from the root package:

```python
>>> import humanize
>>> humanize.Unit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'humanize' has no attribute 'Unit'
>>> humanize.abs_timedelta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'humanize' has no attribute 'abs_timedelta'
```

**Comment by samueljsb** [comment]
Also many of the functions on the [Internationalisation](https://python-humanize.readthedocs.io/en/latest/i18n/) page,. although I think those look like they should be private functions; I'm not sure.

**Comment by hugovk** [comment]
Thanks for the PR!

I wonder if we should instead deprecate these (emit `DeprecationWarning`s) and make them private in the next major release?

(For example, rename `gettext` to `_gettext`, call `_gettext` internally, and have a new `gettext` that emits the warning and calls `_gettext`.)

The functions in question:

`i18n`: `gettext` and `ngettext`.

`time`: `abs_timedelta`, `date_and_delta`, `Unit`

These are all pretty much intended for internal use, that's probably why they weren't made fully public.
