### ISSUE TITLE
Use another augmented assignment statement

### ISSUE THREAD

**Issue by elfring** [jmoiron/humanize#237]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/src/humanize/time.py b/src/humanize/time.py
index f6b7fd6..ca78e48 100644
--- a/src/humanize/time.py
+++ b/src/humanize/time.py
@@ -128,7 +128,7 @@ def naturaldelta(
     seconds = abs(delta.seconds)
     days = abs(delta.days)
     years = days // 365
-    days = days % 365
+    days %= 365
     months = int(days // 30.5)
 
     if not years and days < 1:
```

**Comment by hugovk** [comment]
I think the original is clearer, it mirrors the previous line.
