### ISSUE TITLE
Test contains invalid format string

### ISSUE THREAD

**Issue by RazerM** [jmoiron/humanize#24]
The linked lines in [tests/time.py](https://github.com/jmoiron/humanize/blob/a34c4e86fdc4804d1de287c34e7e007627fbe7c7/tests/time.py#L265,L269) contain the format string `%Y.%M.%D`. This causes the test to fail.

`%M` is "Minute as a zero-padded decimal number." and `%D` doesn't exist.

The correct format is `%Y.%m.%d`.

```
$ nosetests
.......E.....
======================================================================
ERROR: test_naturalday (tests.TimeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\...\tests\time.py", line 269, in test_naturalday
    date(1982, 6, 27).strftime('%Y.%M.%D'), None, "Not a date at all.",
ValueError: Invalid format string

----------------------------------------------------------------------
Ran 13 tests in 0.056s

FAILED (errors=1)

```

**Comment by hugovk** [comment]
Please see PR https://github.com/jmoiron/humanize/pull/90.
