### ISSUE TITLE
Docs for naturaldelta are wrong/incomplete

### ISSUE THREAD

**Issue by carterbox** [jmoiron/humanize#247]
### What did you do?
It seems the docs for `naturaldelta()` are wrong/incomplete/conflicting. They specify that the first parameter should be a `timedelta` or an `int`, but the API will also accept a `datetime`.

### What did you expect to happen?
`naturaldelta()` should only accept `timedelta` or `int` as documented. I expect that users should create their own `timedelta` inline instead of using the `when` parameter.

### What actually happened?
A `datetime` is converted to a `timedelta` internally using the `when` parameter, which defaults to `now`. This undocumented conversion behavior is enforced by the tests.

In the current implementation, the handling of `when` causes and overflow for large `timedeltas` (#245).

### What versions are you using?

* OS: Ubuntu x64
* Python: 3.9.6
* Humanize: 3.13.1

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example) are [self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) with minimal dependencies.

```python
import humanize
from datetime import timedelta, datetime

now = datetime(1, 1, 1, minute=1)
later = datetime(1, 1, 1, minute=31)

# Correct documented usage; input is timedelta.
assert humanize.naturaldelta(later - now) == "30 minutes"

# Incorrect/undocumented usage; input is pair of datetimes
assert humanize.naturaldelta(now, when=later) == "30 minutes"

```

**Comment by carterbox** [comment]
I suspect that the `when` parameter exists because `naturaltime()` was implemented first, and the API was just copied to `naturaldelta()` even though `when` is not appropriate in the later.

**Comment by hugovk** [comment]
The `when` parameter was added to both `naturaltime()` and `naturaldelta()` at the same time, in https://github.com/jmoiron/humanize/pull/144 by @phijor.

Accepting a `datetime` was intentional:

> * both methods may now be used with `datetime` objects that are not in the local timezone

So let's update the docs? @phijor Any thoughts?

**Comment by phijor** [comment]
Accepting `datetime` was done intentionally, but tbf I'm not entirely sure whether that was a good idea?

I agree that the `when`-parameter does not make a lot of sense for `naturaldelta()`.  It is only there to make sure `naturaltime` can be implemented in terms of it.

Maybe the details of both functions should be put in a (private) function as an implementation detail, and `when=` should be removed from `naturaldelta`.  If the behaviour was never specified, is counter-intuitive and leads to issues I'd argue it's not a breaking change to remove it.


Comparing my own use-cases with @carterbox's example, I think computing your own `timedelta` should be encouraged.

**Comment by hugovk** [comment]
We have a major version coming out soon anyway to drop Python 3.6 (https://github.com/jmoiron/humanize/pull/239), so let's deprecate `when=` first and release it, even if it's not long until it's removed.

Would one of you like to submit a PR to deprecate it?

Let's show a warning when `if when:` is true, something along the lines of:

https://github.com/jmoiron/humanize/blob/49f2cd1b8b73e4b63aac5a84b07afcb92c3ca0b7/src/humanize/__init__.py#L40-L45

And add something like "Deprecated, will be removed in humanize 4.0." to the parameter's docstring.

**Comment by carterbox** [comment]
I will submit a PR.
