### ISSUE TITLE
Short scale instead of long scale for Polish locale

### ISSUE THREAD

**Issue by mjmikulski** [jmoiron/humanize#249]
### What did you do?
Read the source code of Polish locale.

### What did you expect to happen?
Have correct translation of `10**9` as "miliard".

### What actually happened?
`10**9` is translated as "bilion".

### What versions are you using?

* OS: NA
* Python: NA
* Humanize: master

Please include **code** that reproduces the issue.
NA

### What is the correct solution?
French locale seems have it done right:
```po
#: src/humanize/number.py:142
msgid "billion"
msgid_plural "billion"
msgstr[0] "milliard"
msgstr[1] "milliard"
```
In Polish we use long scale as in French.

### Who can fix it?
I  would be happy to fix it when I find some time ;)

### Resources
[Long scale vs short scale](https://en.wikipedia.org/wiki/Long_and_short_scale#Long_scale)

**Comment by hugovk** [comment]
The Polish translations are in https://github.com/jmoiron/humanize/blob/master/src/humanize/locale/pl_PL/LC_MESSAGES/humanize.po

A PR would be welcome! You can edit the file directly via the GitHub UI, no need to create a local clone and push.

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
