### ISSUE TITLE
naturaldate returns ambiguous values

### ISSUE THREAD

**Issue by dingens** [jmoiron/humanize#26]
```pycon
>>> import humanize
>>> from datetime import datetime, timedelta
>>> humanize.naturaldate(datetime.now()-timedelta(3))
'Jan 15'
>>> humanize.naturaldate(datetime.now()+timedelta(362))
'Jan 15'
```

I'd suggest to add the year for all dates that are more than about five months away. This would lead to the following output:

| date | naturaldate (executed in Jan 2015) |
| --- | --- |
| 2014-08-20 | Aug 20 |
| 2015-08-20 | Aug 20 2015 |
| 2014-06-20 | Jun 20 2014 |
| 2015-06-20 | Jun 20 |

(Even when only used for dates that are necessarily in the past, like "comment posted on ...", the current behaviour is not perfect: If I read "Jan 19" on Jan 18, 2015, I won't not assume it means Jan 19, 2014.)

**Comment by ncouture** [comment]
Following the same logic I would like to suggest deprecating month name abbreviations that are the current default.

This can be implemented with backward compatibility option that would be to include an argument that allows passing the desired format string when calling the function:

```python
humanize.naturaldate(format="%b %d %Y)
```

The default should be replaced by "%B %d %Y".

**Comment by maix** [comment]
I don't think this has anything to do with this bug, does it?

(btw, I spotted a little typo in my text above. fixed)

**Comment by hugovk** [comment]
@dingens @ludstuen90 @tbille Right now in humanize 1.0, assuming today is Feb 02 2020, the inputs on the left produce the outputs on the right:

```python
        (dt.date(2019, 2, 2), "Feb 02 2019"),
        (dt.date(2019, 3, 2), "Mar 02"),
        (dt.date(2019, 4, 2), "Apr 02"),
        (dt.date(2019, 5, 2), "May 02"),
        (dt.date(2019, 6, 2), "Jun 02"),
        (dt.date(2019, 7, 2), "Jul 02"),
        (dt.date(2019, 8, 2), "Aug 02"),
        (dt.date(2019, 9, 2), "Sep 02"),
        (dt.date(2019, 10, 2), "Oct 02"),
        (dt.date(2019, 11, 2), "Nov 02"),
        (dt.date(2019, 12, 2), "Dec 02"),
        (dt.date(2020, 1, 2), "Jan 02"),
        (dt.date(2020, 2, 2), "today"),
        (dt.date(2020, 3, 2), "Mar 02"),
        (dt.date(2020, 4, 2), "Apr 02"),
        (dt.date(2020, 5, 2), "May 02"),
        (dt.date(2020, 6, 2), "Jun 02"),
        (dt.date(2020, 7, 2), "Jul 02"),
        (dt.date(2020, 8, 2), "Aug 02"),
        (dt.date(2020, 9, 2), "Sep 02"),
        (dt.date(2020, 10, 2), "Oct 02"),
        (dt.date(2020, 11, 2), "Nov 02"),
        (dt.date(2020, 12, 2), "Dec 02"),
        (dt.date(2021, 1, 2), "Jan 02"),
        (dt.date(2021, 2, 2), "Feb 02 2021"),
```

Would something like PR https://github.com/jmoiron/humanize/pull/107 be better?

```python
        (dt.date(2019, 2, 2), "Feb 02 2019"),
        (dt.date(2019, 3, 2), "Mar 02 2019"),
        (dt.date(2019, 4, 2), "Apr 02 2019"),
        (dt.date(2019, 5, 2), "May 02 2019"),
        (dt.date(2019, 6, 2), "Jun 02 2019"),
        (dt.date(2019, 7, 2), "Jul 02 2019"),
        (dt.date(2019, 8, 2), "Aug 02 2019"),
        (dt.date(2019, 9, 2), "Sep 02 2019"),
        (dt.date(2019, 10, 2), "Oct 02"),
        (dt.date(2019, 11, 2), "Nov 02"),
        (dt.date(2019, 12, 2), "Dec 02"),
        (dt.date(2020, 1, 2), "Jan 02"),
        (dt.date(2020, 2, 2), "today"),
        (dt.date(2020, 3, 2), "Mar 02"),
        (dt.date(2020, 4, 2), "Apr 02"),
        (dt.date(2020, 5, 2), "May 02"),
        (dt.date(2020, 6, 2), "Jun 02"),
        (dt.date(2020, 7, 2), "Jul 02"),
        (dt.date(2020, 8, 2), "Aug 02 2020"),
        (dt.date(2020, 9, 2), "Sep 02 2020"),
        (dt.date(2020, 10, 2), "Oct 02 2020"),
        (dt.date(2020, 11, 2), "Nov 02 2020"),
        (dt.date(2020, 12, 2), "Dec 02 2020"),
        (dt.date(2021, 1, 2), "Jan 02 2021"),
        (dt.date(2021, 2, 2), "Feb 02 2021"),
```

It uses `5 * 30.5` as "about 5 months" to decide whether to append the year.

So in this case, gives 4 months before without a year (Oct, Nov, Dev, Jan), and 5 months after without a year (Mar, Apr, May, Jun, Jul).

Would that good enough or should it be more accurate?
