### ISSUE TITLE
Single letter instead of, e.g. "million"?

### ISSUE THREAD

**Issue by Zenahr** [jmoiron/humanize#262]
I haven't found anything in the docs showing this, but would something like:

`10000` -> `10K` be possible? Instead of `10 thousand`

As can be seen here: https://pypi.org/project/ballpark/ (only problem with this lib is that it depends on numpy)

https://github.com/debrouwere/python-ballpark/blob/0b871cdf5b4b5f50e5f3f3d044558801783381c4/ballpark/notation.py#L105

**Comment by hugovk** [comment]
There's a PR for this, please see https://github.com/python-humanize/humanize/pull/1.

(Closing this issue, development has moved to https://github.com/python-humanize/humanize.)
