### ISSUE TITLE
VERSION doesn't match setup.py version

### ISSUE THREAD

**Issue by alimanfoo** [jmoiron/humanize#27]
Minor thing, but the VERSION variable (0, 4) in the package `__init__.py` doesn't match the version reported in setup.py ('0.5.1').

Version for setup.py could be parsed out of `__init__.py`, e.g.: https://github.com/alimanfoo/petl/blob/master/setup.py#L8

Thanks for very handy package!

**Comment by hugovk** [comment]
Will be fixed by https://github.com/jmoiron/humanize/pull/31

**Comment by hugovk** [comment]
Thanks for the report, fixed by https://github.com/jmoiron/humanize/pull/31.
