### ISSUE TITLE
naturaltime returns different results on Windows vs OSX/Linux

### ISSUE THREAD

**Issue by jordanweaver** [jmoiron/humanize#35]
Comparing Windows 7 to *nix (OSX/Linux):

``` python
import datetime, humanize
humanize.naturaltime(datetime.datetime.now() + datetime.timedelta(days=3))
```

Returns `3 days from now` on Windows, but `2 days from now` on the others. I suppose I could interpret either answer as correct, but it feels more correct to say "now + 3 days" = "3 days from now" (siding with Windows, for once). In any case, they should at least agree independent of platform.

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
