### ISSUE TITLE
New PyPI release please

### ISSUE THREAD

**Issue by puittenbroek** [jmoiron/humanize#41]
As title says :)

**Comment by quite** [comment]
Yeah a new release would be great. The package of 0.5.1 in Arch linux AUR now borks on html5lib version...

**Comment by puittenbroek** [comment]
@jmoiron ?

**Comment by s-m-e** [comment]
Great package :) Any update, @jmoiron ? ;)

**Comment by yozlet** [comment]
Try [the luckydonald fork](https://github.com/luckydonald-forks/humanize), on pypi as [lucky-humanize](https://pypi.org/project/lucky-humanize/)

**Comment by hugovk** [comment]
Hello! I'll make a new release soon!

Because it's been a while since the last one, I've made a test release on TestPyPI. If you want to try it out for a smoke test, you can install it something like this:

```bash
pip install -U -i https://test.pypi.org/simple/ humanize
```

**Comment by Chinacolt** [comment]
Please consider including this pull request too #96

**Comment by hugovk** [comment]
@Chinacolt Thank you, merged and will be included! Also included in new test release on TestPyPI: humanize 0.5.2.dev100.

The production release will be 1.0 and I'll probably make it later today or tomorrow.

**Comment by hugovk** [comment]
🚀Five years after the last release, humanize 1.0.0 is now out!

* https://pypi.org/project/humanize/1.0.0/

Thank you everyone for your contributions and patience!
