### ISSUE TITLE
Feature request: naturaltime with UTC support or against arbitrary datetimes

### ISSUE THREAD

**Issue by ddevault** [jmoiron/humanize#46]
```python
humanize.naturaltime(some_date, utc=True)
humanize.naturaltime(some_date, relative_to=datetime.utcnow())
```

**Comment by NotSqrt** [comment]
Quick patch for python3:
```python
from datetime import datetime, timezone
from unittest import mock
from humanize import time as humanize_time

def now():
    return datetime.now(timezone.utc)

def naturaltime(dt):
    if dt.tzinfo is None:
        return humanize_time.naturaltime(dt)
    with mock.patch.object(humanize_time, '_now', side_effect=now):
        return humanize_time.naturaltime(dt)
```

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues

**Comment by ddevault** [comment]
GitHub has a repo move feature which doesn't shove this burden onto literally everyone who has submitted an issue -_-

**Comment by hugovk** [comment]
Sorry about that, unfortunately I don't have admin access to this repo, only write, which is also the reason for the move (to be able to set up integrations to help with maintenance): https://github.com/python-humanize/humanize/issues/3).

Luckily there weren't too many issues here.
