### ISSUE TITLE
999999999 should be '1 billion' but is not

### ISSUE THREAD

**Issue by rtaft** [jmoiron/humanize#59]
9999999999 should return '1.0 billion', however it returns '1000.0 million'

```pycon
>>> import humanize
>>> humanize.number.intword(999999999)
'1000.0 million'

```

**Comment by luc-tielen** [comment]
I can verify that this also happens in other places:
```python
>>> humanize.naturalsize(2 ** 20, binary=True)
'1.0 MiB'
>>> humanize.naturalsize((2 ** 20) - 1, binary=True)
'1024.0 KiB'
```

Any updates on this?

**Comment by hugovk** [comment]
@rtaft @luc-tielen There's a fix coming in https://github.com/jmoiron/humanize/pull/113, would you like to test it?
