### ISSUE TITLE
reverse humanize. from "1 billion" to in value  

### ISSUE THREAD

**Issue by arianpasquali** [jmoiron/humanize#63]
This is an amazing lib. Well done!!
I wonder if it is possible a reverse function.

I have a string "1 billion" and I want to convert to int.

Is is doable with the lib? I could not find it in the tests.

Congrats

**Comment by hugovk** [comment]
No, this only converts the other way. You could use https://pypi.org/project/word2number/

```pycon
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from word2number import w2n
>>> w2n.word_to_num("1 billion")
1000000000
>>>
```

Thanks!
