### ISSUE TITLE
pypi page looks strange

### ISSUE THREAD

**Issue by guettli** [jmoiron/humanize#65]
https://pypi.org/project/humanize/

AFAIK they do not support markdown, you need to format the README in restructed text.

**Comment by rachmadaniHaryono** [comment]
as of march 16 2018, pypi support markdown 

guide: https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

but it need new release 

related #41 #58

**Comment by hugovk** [comment]
The current README is RST, so should be fine when making a new release with updated tools (twine, setuptools, etc.).

If not, it could be converted to MD and the metadata updated according to that article.

**Comment by hugovk** [comment]
It should be fine with the next release, see an example on TestPyPI:

* https://test.pypi.org/project/humanize/

Thanks for the report!
