### ISSUE TITLE
Timedelta: "ago" does not always match

### ISSUE THREAD

**Issue by guettli** [jmoiron/humanize#66]
I am not a native english speaker, but I think the word "ago" does not match to all timedeltas.

For me "ago" means "before the current moment".

If I want to show the timedelta (duration) of a job which was executed some days in the past, and this job took 10 seconds, then "10 seconds ago" does not match.

What do you think?

**Comment by ddevault** [comment]
I just encountered the same problem.

**Comment by hugovk** [comment]
Please could you share a small code sample to illustrate it?

**Comment by ddevault** [comment]
I think humanize.naturaldelta solves this.

**Comment by hugovk** [comment]
OK, good to hear, I'll close this.
