### ISSUE TITLE
'decimal': ('kB'）, the 'k' must be upper.

### ISSUE THREAD

**Issue by genghaos** [jmoiron/humanize#67]
```python
suffixes = {
    'decimal': ('kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'),
    'binary': ('KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB'),
    'gnu': "KMGTPEZY",
}
```

==> the first letter of 'kB', 'k' must be upper.

**Comment by ernestask** [comment]
…no? https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes

**Comment by hugovk** [comment]
Thanks for the report.

The SI prefix for kilo uses a small "k":

* https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes

Sometimes "KB" is used for kilobyte, but to be unambiguous, "kB" is used for decimal = base 10 = 1000 bytes:

* https://en.wikipedia.org/wiki/Kilobyte#Base_10_(1000_bytes)

And "KB" or "K" for binary = base 2 = 1024 bytes, aka "kibibyte" or "KiB":

* https://en.wikipedia.org/wiki/Kilobyte#Base_2_(1024_bytes)
