### ISSUE TITLE
Which fork of this project is the most promissing one? 

### ISSUE THREAD

**Issue by deeplook** [jmoiron/humanize#68]
Apparently, this is an abandoned project, so the natural question is which fork should be considered the most promising to pick instead?

**Comment by em92** [comment]
Original one looks find so far.
But if you ask - https://github.com/luckydonald-forks/humanize

**Comment by ProoffreaderDotCom** [comment]
@em92, its README says it's only compatible to Python 3.3.

**Comment by danyalejandro** [comment]
> @em92, its README says it's only compatible to Python 3.3.

Might be because most of the core Python packages will soon require Python 3, as the end of life for Python 2 happens in a few months.

**Comment by ohk2kt3t4** [comment]
I think he means that the wording makes it sounds like the package is not compatible with 3.4+

**Comment by danyalejandro** [comment]
Right, my bad.

**Comment by hugovk** [comment]
I've revived this project and there'll be a new release soon: https://github.com/jmoiron/humanize/issues/41
