### ISSUE TITLE
humanize.apnumber(0) should return zero

### ISSUE THREAD

**Issue by itemir** [jmoiron/humanize#72]
`humanize.appnumber` returns 0 for 0, while (I think) it should return 'zero':

```pycon
>>> import humanize
>>> humanize.apnumber(0)
'0'
>>> humanize.apnumber(1)
'one'
>>> humanize.apnumber(2)
'two'
>>>
```

**Comment by itemir** [comment]
I just saw the following note in the code:

`For numbers 1-9, returns the number spelled out. Otherwise, returns the
number. This follows Associated Press style.  This always returns a string
unless the value was not int-able, unlike the Django filter.`

I don't know why AP omitted zero but I think it makes sense to spell it out. That being said, feel free to close this if you think otherwise.

**Comment by hugovk** [comment]
Looking this up, apparently the _Associated Press Stylebook_ (p. 203) says:

* **Spell out whole numbers up to (and including) nine** (e.g., zero, one, 10, 96, 104).

https://apvschicago.com/2011/05/numbers-spell-out-or-use-numerals.html

Please see PR https://github.com/jmoiron/humanize/pull/121 to fix this.
