### ISSUE TITLE
Stop requiring __file__

### ISSUE THREAD

**Issue by gjcarneiro** [jmoiron/humanize#81]
I wanted to embed humanize in a pyoxidizer binary, but it uses `__file__`, which pyoxidizer doesn't support.

See https://github.com/indygreg/PyOxidizer/issues/69

**Comment by hugovk** [comment]
Thanks for the report. A pull request to fix this is welcome.

**Comment by hugovk** [comment]
Fixed and released in 2.4.1!

https://github.com/jmoiron/humanize/releases/tag/2.4.1
