### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by hugovk** [jmoiron/humanize#85]
@jmoiron Hi Jason! Thank you very much for this project!

It's been three years since an update, and there's quite a few PRs. This project is quite widely used (560k downloads last month according to https://pypistats.org/packages/humanize!), and it'd be great to keep things ticking over.

I understand if you've moved on and have other interests. Please would you consider giving merge and PyPI rights to one or more extra maintainers?

I'd like to volunteer, especially to help with some of the maintenance tasks and to get a new release out. I could modernise the codebase for current Python versions, add testing with pytest and linting on GitHub Actions (I've made a start in https://github.com/jmoiron/humanize/pull/84).

I've gone through the PRs and approved some I think are good to merge, and commented some others that could use a bit extra work.

Additionally to consider, a transfer to https://jazzband.co, which provides additional maintainer backup. 

What do you think? 

Again, thank you for this project!

Edit: Also emailed this to Jason.

**Comment by hugovk** [comment]
Jason has given me repo merge rights and will also add me to PyPI. I'll merge some PRs and then prepare a new release. Thanks!

**Comment by jmoiron** [comment]
Thank you :)
